export const actionTypes = {
    LOAD_USERS_START: "LOAD_USERS_START",
    LOAD_USERS_SUCCESS: "LOAD_USERS_SUCCESS",
    LOAD_USERS_ERROR: "LOAD_USERS_ERROR",

    CREATE_USER_START: "CREATE_USER_START",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_ERROR: "CREATE_USER_ERROR",

    DELETE_USER_START: "DELETE_USER_START",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_ERROR: "DELETE_USER_ERROR",

    UPDATE_USER_START: "UPDATE_USER_START",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_ERROR: "UPDATE_USER_ERROR"
}